version: '2'
services:
    billingmodule-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BillingModule/mongodb/:/data/db/
